import datetime as dt
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import rg_ifft_df_i as ift

fig, ax = plt.subplots()

MyPath = 'C:/Users/Masamichi Sato/PycharmProjects/RG'

# change to the appropriate file name generated by R
xd = pd.read_csv(r'C:/Users/Masamichi Sato/PycharmProjects/RG/boot_dat2_BRD3187_40000.csv', delimiter=',')
row, col = xd.shape

print(row, col)
print(dt.datetime.now())

x = xd.iloc[:,1]

def res_theta(dat):
    def of(param):
        res = ift.f1(x, param)
        r = dat - res[1]
        return r

    initialValue = np.array([1, 2, 1, 1])  # for 50_g
    # initialValue = np.array([1,2,1,60])#for 5_sl
    # initialValue = np.array([1,2,1,100])#for 3_sl
    # initialValue = np.array([1,2,1,80])#for 30_sl
    # initialValue = np.array([1,2,1,4])#for xr for 4780kbp
    # initialValue = np.array([1,2,1,3])#for xr2 for 4780kbp
    # initialValue = np.array([1,2,1,0.5])#for xr3 for 4780kbp
    # initialValue = np.array([1,2,1,2])#for xr for 500kbp
    # initialValue = np.array([1,2,1,2])#for xr2 for 500kbp
    # initialValue = np.array([1,2,1,2])#for xr3 for 500kbp

    df = np.array([1] * len(x))
    initialValue = np.append(initialValue, df)
    bl = np.array([0, 0, 0, 0])
    bl = np.append(bl, np.array([0.01] * len(x)))
    bu = np.array([5, 5, 4, 400])
    bu = np.append(bu, np.array([50] * len(x)))
    bb = np.array([bl, bu])
    bb = bb.reshape([2, len(x) + 4])
    betaID = ift.ev(of, initialValue, bb)
    popt = betaID.x

    return popt

for i in range(col-2):
    y = xd.iloc[:, i+2]
    bb = res_theta(y)
    th = bb[0]
    gm = bb[1]
    nn = bb[2]
    kbt = bb[3]
    if i == 0:
        pp_th = th
        pp_gm = gm
        pp_nn = nn
        pp_kbt = kbt
    else:
        pp_th = np.append(pp_th, th)
        pp_gm = np.append(pp_gm, gm)
        pp_nn = np.append(pp_nn, nn)
        pp_kbt = np.append(pp_kbt, kbt)

    print(i)

print(pp_th)
print(np.mean(pp_th))
print(np.std(pp_th))
print(np.std(pp_th)/np.sqrt(len(pp_th)))
np.savetxt(os.path.join(MyPath, 'boot_res2_theta_BRD3187.csv'), pp_th, delimiter=',')
np.savetxt(os.path.join(MyPath, 'boot_res2_gamma_BRD3187.csv'), pp_gm, delimiter=',')
np.savetxt(os.path.join(MyPath, 'boot_res2_nn_BRD3187.csv'), pp_nn, delimiter=',')
np.savetxt(os.path.join(MyPath, 'boot_res2_kbt_BRD3187.csv'), pp_kbt, delimiter=',')

print(dt.datetime.now())
