import datetime as dt
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import rg_ifft_df as ift

fig, ax = plt.subplots()

MyPath = # path to your folder

# change to the appropriate file name generated by R
xd = np.loadtxt(os.path.join(MyPath, 'dis_data_BRD3179_50_g.csv'), delimiter=',', skiprows=1, usecols=[1, 2])
row, col = xd.shape
x = xd[0:row, 0]
y = xd[0:row, 1]

print(dt.datetime.now())


def of(param):
    res = ift.f1(x, param)
    r = y - res[1]
    return r


initialValue = np.array([1, 2, 1, 1])  # for 50_g
# initialValue = np.array([1,2,1,60])#for 5_sl
# initialValue = np.array([1,2,1,100])#for 3_sl
# initialValue = np.array([1,2,1,80])#for 30_sl
# initialValue = np.array([1,2,1,4])#for xr for 4780kbp
# initialValue = np.array([1,2,1,3])#for xr2 for 4780kbp
# initialValue = np.array([1,2,1,0.5])#for xr3 for 4780kbp
# initialValue = np.array([1,2,1,2])#for xr for 500kbp
# initialValue = np.array([1,2,1,2])#for xr2 for 500kbp
# initialValue = np.array([1,2,1,2])#for xr3 for 500kbp

df = np.array([1] * len(x))
initialValue = np.append(initialValue, df)
bl = np.array([0, 0, 0, 0])
bl = np.append(bl, np.array([0.01] * len(x)))
bu = np.array([5, 5, 4, 400])
bu = np.append(bu, np.array([50] * len(x)))
bb = np.array([bl, bu])
bb = bb.reshape([2, len(x) + 4])
betaID = ift.ev(of, initialValue, bb)

p = np.array(betaID.x)
yre = ift.f1(x, p)

print(dt.datetime.now())

print(x)
print(y)
print(yre[1])
print(y - yre[1])
print(p)

# change to the appropriate file name
pd.DataFrame(p).to_csv(os.path.join(MyPath, 'inf_param_df_BRD3179_50_g.csv'))
pd.DataFrame(np.vstack((x, y))).to_csv(os.path.join(MyPath, 'yo_df_BRD3179_50_g.csv'))
pd.DataFrame(np.vstack((yre[0], yre[1]))).to_csv(os.path.join(MyPath, 'yre_df_BRD3179_50_g.csv'))

c1, c2 = "red", "green"  # plot color
l1, l2 = "obs", "inv_F"  # label

ax.set_xlabel('x')  # x label
ax.set_ylabel('y')  # y label
ax.set_aspect('equal')  # adjust scale
ax.grid()  # grid
ax.set_xlim([np.min(x), np.max(x)])
ax.set_ylim([np.min(np.array([np.min(y), np.min(yre[1])])), np.max(np.array([np.max(y), np.max(yre[1])]))])
ax.plot(x, y, color=c1, label=l1)
ax.plot(yre[0], yre[1], color=c2, label=l2)
# for precise comparison
# ax.set_ylim([np.min(np.array([np.min(10*(y-y[0])),np.min(10* (yre[1]-yre[1][0]))])), np.max(np.array([np.max(10*(y-y[0])),np.max(10* (yre[1]-yre[1][0]))]))])
# ax.plot(x, 10*(y-y[0]), color=c1, label=l1)
# ax.plot(yre[0],10* (yre[1]-yre[1][0]), color=c2, label=l2)
ax.legend(loc=0)  # legend
fig.tight_layout()  # layout
plt.savefig('res_df_BRD3179_50_g.png')  # save image
plt.show()
